name: CICD
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    name: Semantic Release
    steps:
      - uses: actions/checkout@v2
      - uses: cycjimmy/semantic-release-action@v2.5.0
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
